# Do not change any values if you do not know what they do. 
# Doing so could break the weatherstation!

sensors:
    temp_pin: 14 # Pin number for the Adafruit DHT temperature/humidity sensor
server:
    host: 67.205.153.103 # URL to the weather station website
    port: 5000 # Port of the express server that is accepting data